<h1>Upcoming championshipdays</h1>
<?php echo $this->render('includes/datagrid/default.phtml'); ?>
<table>
    <tr>
        <th>Championshipday</th>
        <th>Date</th> 
        <th>Registration</th>
    </tr>
    <tr>
<?php   foreach($this->upcomingChampionshipdays as $upcomingChampionshipday) { ?>
            <td><a href="/championshipday/registration/id/<?php echo $upcomingChampionshipday['ID'];?>"><?php echo $upcomingChampionshipday['Description']; ?></a></td>
            <td><?php echo $upcomingChampionshipday['Date']; ?></td>
            <td><?php echo $upcomingChampionshipday['Registration'] ? 'OK' : 'NOK'; ?></td>
<?php   } ?>
    </tr>
</table>
<h1>Past championshipdays</h1>
<table>
    <tr>
        <th>championshipdays</th>
        <th>Date</th> 
    </tr>    

<?php   foreach($this->pastChampionshipdays as $pastChampionshipday) { ?>
            <tr>
                <td><a href="/championshipday/registration/id/<?php echo $pastChampionshipday['ID'];?>"><?php echo $pastChampionshipday['Description']; ?></a></td>
                <td><?php echo $pastChampionshipday['Date']; ?></td>
            </tr>
<?php   } ?>
    </tr>
</table>