<?php 
$this->placeholder('mainTitle')->set('championshipday');

// --------------------------------
if (!empty($this->championshipday)){
    echo $this->championshipdayHelper('viewInfo',array('data' => $this->championshipday));
}

if (!empty($this->messages)){ ?>
    <div class="msg_ok" style="color:white;">
<?php   foreach($this->messages as $v){
            echo $this->escape($v) . '<br />' .  PHP_EOL;
        } ?>
    </div>
<?php }

//@todo: view helper
$this->tabPane('myTabContainer', $this->partial('championshipday/tab-championshipday.phtml',array('championshipday' => $this->championshipday,'form' => $this->form)),array('title' => $this->translate('Championshipday',3)));

if (!empty($this->championshipday)){
    $this->tabPane('myTabContainer', $this->partial('championshipday/tab-registration.phtml',array(
                                                    'championshipday'   => $this->championshipday,
                                                    'content'      => $this->tabs['registration'],
                                                )
					),array('title' => $this->translate('Registrations',3)));
    $this->tabPane('myTabContainer', $this->partial('championshipday/tab-game.phtml',array(
                                                    'championshipday'   => $this->championshipday,
                                                    'content'      => $this->tabs['game'],
                                                )
					),array('title' => $this->translate('Games',3)));
}
//Zend_Debug::dump($this->tabs['game']);
echo $this->tabContainer('myTabContainer',
                            array('selected' => $this->selectedTabIndex),
                            array('class' => 'start', 'width' => 300),
                            array('class' => 'start')
						
);

?>