<?php 
$this->jQuery()->onLoadCaptureStart();
?>
$('table.borders tr.row').hover(function(){
			$(this).children().addClass('datahighlight');
		},function(){
			$(this).children().removeClass('datahighlight');
		}).css({cursor: 'hand'});        

<?php 
$this->jQuery()->onLoadCaptureEnd();

$this->headLink()->prependStylesheet('/base/datagrid/styles/default.css');
if (!empty($this->messages)){ ?>
    <div class="msg_ok" style="color:white;">
<?php   echo $counter = 0;
        foreach($this->messages as $v){
            echo $this->escape($v) . '<br />' .  PHP_EOL;
        } ?>
    </div>
<?php } ?>

<div style="width:1000px;overflow:auto;<?php echo $this->style; ?>">
    <?php echo $this->datagrid; ?>
</div>